org: caiomoura1994
app: serverless-node-express-dynamo
service: aws-node-express-dynamodb-api-project
frameworkVersion: '3'

custom:
  tableName: 'users-table-${sls:stage}'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:CreateTable
            - dynamodb:DescribeTable
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}
    PUBLIC_KEY: 'bbdd71958be9dccdb0ddd9ec9a164f47c6e8b84357ccea52df0c1e0081824634'

functions:
  cronHandler:
    handler: notifyBirthday.run
    events:
      - schedule: cron(0 15 * * ? *)
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          # - AttributeName: wallet
          #   AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: birthday
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          # - AttributeName: wallet
          #   KeyType: RANGE
          - AttributeName: birthday
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
